### ISSUE TITLE
[Feature] Add get a copy/buy links

### ISSUE THREAD

**Issue by libreom** [nesaku/BiblioReads#15]
**Is your feature request related to a problem/an inconvenience? Please describe.**
I want to buy/get a book which I see in biblioreads

**Describe the solution/feature you'd like**
Add many get a copy links from various sources like Amazon, kindle, audible, abebooks ,library etc Also add libgen, Anna's archive , z-library link if possible

**Describe alternatives you've considered**
Libgen, Anna's archive's links only

**Additional context**
![Screenshot_20231125-123443_Brave.jpg](https://github.com/nesaku/BiblioReads/assets/111110599/0034048d-f888-4ebe-8f07-674d4cabb814)

**Comment by nesaku** [comment]
Hello libreom, 
Thank you for the feature request. Amazon, Audible, AbeBooks, Barnes & Noble and Libraries links have been added in https://github.com/nesaku/BiblioReads/commit/f71a430897d3327083267dbcb5edeb5eae7ebbd8 (v2.16.0). Libgen, Anna's archive and Z-library have not been added because of their questionable legality.
